version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    tty: true
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "8080:8080" #DEBUG PORT
    volumes:
      - ./backend:/usr/src/app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./frontend:/usr/src/app
    environment:
     - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
