version: '3'

services:
  backend:
    container_name: backend_container
    build:
      context: ./backend
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    # command: sh -c "python manage.py runserver 0.0.0.0:8000"
    command: sh -c "python -m debugpy --listen 0.0.0.0:8080 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./frontend:/usr/src/app
    environment:
     - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
