version: '3'

services:
  backend:
    build:
      context: ./backend
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "npm install && npm run dev"
