# Generated by Django 3.2.25 on 2024-08-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
